### PR TITLE
updates based on PR 1 review

### PR DESCRIPTION
**Pull request by LiNk-NY**
@almahmoud 
This should resolve some of the comments in the review for https://github.com/Bioconductor/BiocWorkshopSubmit/pull/1

### CODE REVIEW

**Comment by almahmoud** [comment]
Re the git vs Github, i'm wondering if it's possible to have the top field that is used for the populating be github only, but leaving the "source" field in the command to be freeform any git url? Mostly useful for package demos where people have used it before to just specify the git.bioconductor.org source and vignettes in it

**Comment by LiNk-NY** [comment]
Thanks for the suggestion. I've reverted the previous one https://github.com/Bioconductor/BiocWorkshopSubmit/commit/417e83f85de1ad1f54f445ae18369a73283e39d5 and renamed the field to `gitrepo`.
I am not too familiar with how the `source` field is used but I suppose that it can work with other git repositories.

**Comment by almahmoud** [comment]
Tysm, LGTM! I'll update the live version after merge

**Comment by LiNk-NY** [comment]
BTW @almahmoud 
Only you can merge :)

**Comment by almahmoud** [comment]
I thought it was still a PR on the Bioconductor repo, I should've paid more attention, sorry...

**Pull request merged**
